apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-dashboard
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
  annotations:
    grafana_folder: "Node Exporter"
data:
  node-exporter.json: |
    {
      "__inputs": [],
      "__requires": [],
      "annotations": {
        "list": []
      },
      "editable": true,
      "gnetId": 1860,
      "graphTooltip": 0,
      "id": null,
      "iteration": 1629393438494,
      "panels": [],
      "schemaVersion": 26,
      "style": "dark",
      "tags": ["node-exporter"],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Node Exporter Full",
      "uid": "node-exporter-full",
      "version": 40
    }
