apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`flask.elysium-space.com`)  # Replace with your domain
      kind: Rule
      services:
        - name: {{ .Release.Name }}  # Replace with your Flask service name
          port: 80
