name: Terraform Plan and Apply

on:
  push:
    branches:
      - task_1
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Format
        run: |
          pwd
          ls -la
          terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          pwd
          ls -la
          terraform init
        working-directory: task_1/project

      - name: Terraform Plan
        run: |
          pwd
          ls -la
          terraform plan
        working-directory: task_1/project

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: |
          pwd
          ls -la
          terraform apply -auto-approve
        working-directory: task_1/project
