name: Terraform Plan and Apply

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  TASK: task_2
  TF_VERSION: ${{ secrets.TF_VERSION }} # Set this in GitHub Secrets
  AWS_REGION: ${{ secrets.AWS_REGION }} # Set this in GitHub Secrets
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} # Set this in GitHub Secrets
  VPC_CIDR: ${{ secrets.VPC_CIDR }} # Set this in GitHub Secrets
  AZS: ${{ secrets.AZS }} # Set this in GitHub Secrets
  PUBLIC_SUBNET_CIDRS: ${{ secrets.PUBLIC_SUBNET_CIDRS }} # Set this in GitHub Secrets
  PRIVATE_SUBNET_CIDRS: ${{ secrets.PRIVATE_SUBNET_CIDRS }} # Set this in GitHub Secrets
  ALLOWED_SSH_CIDR: ${{ secrets.ALLOWED_SSH_CIDR }} # Set this in GitHub Secrets
  KEY_PAIR: ${{ secrets.KEY_PAIR }} # Set this in GitHub Secrets
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for commenting on PRs

permissions:
  id-token: write  # Required for OIDC token exchange
  contents: read   # Required to checkout the repo
  pull-requests: write  # Required to comment on PRs
  actions: read   # Required to upload artifacts
  issues: write   # Required to comment on issues
  checks: write   # Required to update checks on PRs
  statuses: write # Required to update commit statuses

jobs:
  terraform-format:
    name: Terraform Format
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        run: terraform fmt -check -recursive

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionRole # AWS Account ID should be set in GitHub Secrets
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TASK }}/project

      - name: Terraform Plan
        run: |
          terraform plan -out=output.tfplan \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="aws_account_id=${{ env.AWS_ACCOUNT_ID }}" \
            -var="vpc_cidr=${{ env.VPC_CIDR }}" \
            -var="azs=${{ env.AZS }}" \
            -var="public_subnet_cidrs=${{ env.PUBLIC_SUBNET_CIDRS }}" \
            -var="private_subnet_cidrs=${{ env.PRIVATE_SUBNET_CIDRS }}" \
            -var="allowed_ssh_cidr=${{ env.ALLOWED_SSH_CIDR }}" \
            -var="key_pair=${{ env.KEY_PAIR }}"
        working-directory: ${{ env.TASK }}/project

      - name: Terraform Show to file
        if: github.event_name == 'pull_request'
        run: terraform show -no-color output.tfplan > tfplan.txt
        working-directory: ${{ env.TASK }}/project

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            output.tfplan
            tfplan.txt

      - name: Comment Plan on PR
        if: github.event_name == 'pull_request'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "$(cat ${{ env.TASK }}/project/tfplan.txt | head -c 65000)"
        env:
          GH_TOKEN: ${{ env.GH_TOKEN }}

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionRole # AWS Account ID should be set in GitHub Secrets
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TASK }}/project

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Terraform Apply
        run: terraform apply -auto-approve output.tfplan
        working-directory: ${{ env.TASK }}/project

  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TASK }}/project

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="aws_account_id=${{ env.AWS_ACCOUNT_ID }}" \
            -var="vpc_cidr=${{ env.VPC_CIDR }}" \
            -var="azs=${{ env.AZS }}" \
            -var="public_subnet_cidrs=${{ env.PUBLIC_SUBNET_CIDRS }}" \
            -var="private_subnet_cidrs=${{ env.PRIVATE_SUBNET_CIDRS }}" \
            -var="allowed_ssh_cidr=${{ env.ALLOWED_SSH_CIDR }}" \
            -var="key_pair=${{ env.KEY_PAIR }}"
        working-directory: ${{ env.TASK }}/project
