name: Terraform Plan and Apply

on:
  push:
    branches:
      - task_1
  pull_request:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC token exchange
  contents: read   # Required to checkout the repo

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.12.0

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionRole # AWS Account ID should be set in GitHub Secrets
          aws-region: eu-north-1

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init
        working-directory: task_1/project

      - name: Terraform Plan
        run: terraform plan -out=output.tfplan
        working-directory: task_1/project

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve output.tfplan
        working-directory: task_1/project
