name: Terraform Plan and Apply

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0
          
      - name: Debug workspace
        run: |
          echo "Current path: $(pwd)"
          ls -la
          ls -la task_1
          ls -la task_1/project || echo "Directory task_1/project does not exist"

      - name: Terraform Init
        run: terraform init
        working-directory: task_1/project

      - name: Terraform Plan
        run: terraform plan
        working-directory: task_1/project

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: task_1/project
