name: Terraform Plan and Apply

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          cd ./task_1/project
          terraform init

      - name: Terraform Plan
        run: |
          cd ./task_1/project
          terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: |
          cd ./task_1/project
          terraform apply -auto-approve
