name: Test AWS OIDC Role Assumption

on:
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC token exchange
  contents: read   # Required to checkout the repo

jobs:
  assume-role-and-test:
    name: Assume AWS IAM Role and Run AWS CLI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::767398122881:role/GithubActionRole
          aws-region: eu-north-1

      - name: Verify caller identity
        run: aws sts get-caller-identity
